### ISSUE TITLE
sayid breaks emacs-cider compilation for specific projects

### ISSUE THREAD

**Issue by paulrd** [bpiel/sayid#37]
I tracked down a weird bug in spacemacs-develop branch to the addition of the sayid package at this  [commit.](https://github.com/syl20bnr/spacemacs/commit/cfe0295875e78c7a29df48b1e07e06650c5c3988#diff-2a8459f655b4c71c7f7a6c8b773322f9)
I had been working with some cider-emacs people to track down the strange bug [here.](https://github.com/clojure-emacs/cider/issues/2236)
I was wondering if you could look into it.

**Comment by paulrd** [comment]
Inclusion of tools.nrepl in project dependencies may not be required to produce the bug (it was intermittently required for me to reproduce the bug but no longer needed).

**Comment by bpiel** [comment]
@paulrd I'm able to reproduce the bug and have confirmed that upgrading sayid to `[org.clojure/tools.reader "1.3.0-alpha3"]` fixes it.

The tests pass, but I'm going to make sure nothing breaks for me during use today before I do a release.

I'll post here once the fix is release. Thanks for tracking this down.

**Comment by bpiel** [comment]
@paulrd This took me much longer to get to than I expected, but it's done. It should hit melpa within a few hours, I believe.

https://github.com/bpiel/sayid/commit/8ea70573e6eb1a0d1a450fd501f38c2cf26ce27f
